Use `--no-binary lxml` now that newer pip broke `--no-binary`
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 435, in _handle_no_binary
    value, existing.no_binary, existing.only_binary,
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pip/_internal/models/format_control.py", line 46, in handle_mutual_excludes
    "--no-binary / --only-binary option requires 1 argument."
pip._internal.exceptions.CommandError: --no-binary / --only-binary option requires 1 argument.

https://travis-ci.org/ArchiveTeam/grab-site/builds/600264421